name: gamblers-dice
version: git
summary: A terrible idea, now real.
description: |
  The term Gambler's fallacy refers to a misconception about statistics. [...]
  In statistics, a random event has a certain probability of occurring. The
  fallacy is that if the event has occurred less frequently in the past, it
  will be more frequent in the future. -Wikipedia

  Well no longer is this a fallacy my friends, these dice are real! If you roll
  a 20 sided die, and you haven't seen a 20 in a while it is statistically more
  likely to show up in the next roll with these dice. And the best part, it's
  still uniformly random for large sample sets!

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  server:
    command: sh -c \"cd $SNAP/lib/node_modules/gamblers-dice && http-server -a localhost -p 8080\"
    plugs: [network-bind]
    daemon: simple

parts:
  gamblers-dice:
    source: .
    plugin: nodejs
    node-packages: [http-server]
